const { Pool } = require("pg")
require("dotenv").config()

/* ***************
 * Connection Pool
 * SSL Object needed for local testing of app
 * *************** */
let pool
if (process.env.NODE_ENV == "development") {
  pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: {
      rejectUnauthorized: false,
    },
  })
} else {
  pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: {
      rejectUnauthorized: false,
    },
  })
}

// Intercept query to log it (optional, but keep it simple for now)
const originalQuery = pool.query;
pool.query = async function (text, params) {
  try {
    const res = await originalQuery.apply(this, [text, params]);
    // console.log("Executed query:", text);
    return res;
  } catch (error) {
    console.error("Error in query:", text);
    throw error;
  }
};

// Ensure favorites table exists (helps local dev if migration wasn't run)
;(async function ensureFavoritesTable() {
  try {
    const sql = `
      CREATE TABLE IF NOT EXISTS public.user_favorites (
        favorite_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        account_id integer NOT NULL,
        inv_id integer NOT NULL,
        CONSTRAINT user_favorites_pkey PRIMARY KEY (favorite_id),
        CONSTRAINT uq_user_inv UNIQUE (account_id, inv_id),
        CONSTRAINT fk_fav_account FOREIGN KEY (account_id) REFERENCES public.account(account_id) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT fk_fav_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory(inv_id) ON DELETE CASCADE ON UPDATE CASCADE
      );
    `
    await pool.query(sql)
    // no logging to keep startup quiet
  } catch (err) {
    // If DB isn't available at startup, log and continue; server will show DB errors elsewhere
    console.error('Could not ensure user_favorites table:', err.message || err)
  }
})()

module.exports = pool